services:
  samba:
    container_name: samba-ad-dc
    image: euca01/samba-ad-dc:main
    env_file:
      - path: ./samba.env
        required: true
    restart: unless-stopped
    volumes:
      - /opt/smb-conf:/etc/samba
      - type: bind
        source: /opt/krb-conf/krb5.conf
        target: /etc/krb5.conf
      - /opt/smb-data:/var/lib/samba
      - /opt/krb-data:/var/heimdal
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "88:88/tcp"
      - "88:88/udp"
      - "135:135/tcp"
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "389:389/tcp"
      - "389:389/udp"
      - "445:445/tcp"
      - "464:464/tcp"
      - "464:464/udp"
      - "636:636/tcp"
      - "3268:3268/tcp"
      - "3269:3269/tcp"

  chrony:
    image: euca01/chrony:main
    cap_add:
      - ALL
    container_name: ntp
    restart: unless-stopped
    ports:
      - 123:123/udp
    env_file:
      - path: ./samba.env
        required: true
    environment:
      - LOG_LEVEL=0
      - NOCLIENTLOG=true
      - ENABLE_NTS=false
      - ENABLE_SYSCLK=true