services:
  samba:
    container_name: samba-ad-dc
    image: tkaefer/alpine-samba-ad-container
    environment:
      - SAMBA_DOMAIN=ESITC
      - SAMBA_REALM=ESITC.PARIS
      - SAMBA_ADMIN_PASSWORD=sitec2024$
      - KERBEROS_PASSWORD=sitec2024$
      - SAMBA_HOST_IP=192.168.181.10
    volumes:
      - /opt/smb-conf:/etc/samba
      - type: bind
        source: /opt/krb-conf/krb5.conf
        target: /etc/krb5.conf
      - /opt/smb-data:/var/lib/samba
      - /opt/krb-data:/var/lib/krb5kdc
    network_mode: "host"