version: '2'
services:
  samba:
    image: tkaefer/alpine-samba-ad-container
    environment:
      - SAMBA_DOMAIN=ESITC
      - SAMBA_REALM=ESITC.PARIS
    volumes:
      - /opt/smb-conf:/etc/samba
      - /opt/krb-conf/krb5.conf:/etc/krb5.conf
      - /opt/smb-data:/var/lib/samba
      - /opt/krb-data:/var/lib/krb5kdc
    ports:
      - "22:22"
      - "53:53"
      - "389:389"
      - "88:88"
      - "135:135"
      - "139:139"
      - "138:138"
      - "445:445"
      - "464:464"
      - "3268:3268"
      - "3269:3269"
