services:
  samba:
    container_name: samba-ad-dc
    image: euca01/samba-ad-dc:main
    environment:
      - SAMBA_DOMAIN=ESITC
      - SAMBA_REALM=ESITC.PARIS
      - SAMBA_ADMIN_PASSWORD=ChangePassword$5
      - KERBEROS_PASSWORD=ChangePassword$5
      - SAMBA_HOST_IP=192.168.181.10
    restart: unless-stopped
    volumes:
      - /opt/smb-conf:/etc/samba
      - type: bind
        source: /opt/krb-conf/krb5.conf
        target: /etc/krb5.conf
      - /opt/smb-data:/var/lib/samba
      - /opt/krb-data:/var/heimdal
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "88:88/tcp"
      - "88:88/udp"
      - "135:135/tcp"
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "389:389/tcp"
      - "389:389/udp"
      - "445:445/tcp"
      - "464:464/tcp"
      - "464:464/udp"
      - "636:636/tcp"
      - "3268:3268/tcp"
      - "3269:3269/tcp"




docker run -e SAMBA_DOMAIN='ESITC' -e SAMBA_REALM='ESITC.PARIS' -e SAMBA_ADMIN_PASSWORD='YOURpassword$5' -e KERBEROS_PASSWORD='YOURpassword$5' -e SAMBA_HOST_IP='192.168.181.10' testsamba:latest