services:
  samba:
    hostname: DEFAULT_DOCKERHOST
    container_name: samba-ad-dc
    image: euca01/samba-ad-dc:main
    env_file:
      - path: ./samba.env
        required: true
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /opt/smb-conf:/etc/samba
      - type: bind
        source: /opt/krb-conf/krb5.conf
        target: /etc/krb5.conf
      - /opt/smb-data:/var/lib/samba
      - /opt/krb-data:/var/heimdal
#    ports:
#      - "5353:53/udp"
##      - "5353:53/tcp"
#      - "88:88/tcp"
#      - "88:88/udp"
#      - "135:135/tcp"
#      - "137:137/udp"
#      - "138:138/udp"
#      - "139:139/tcp"
#      - "389:389/tcp"
#      - "389:389/udp"
#      - "445:445/tcp"
#      - "464:464/tcp"
#      - "464:464/udp"
#      - "636:636/tcp"
#      - "3268:3268/tcp"
#      - "3269:3269/tcp"

  bind9:
    image: euca01/bind9-alpine:main
    container_name: bind9
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/bind9-conf/named.conf
        target: /etc/bind/named.conf
    ports:
      - "5354:53/udp"
      - "5354:53/tcp"
    depends_on:
      - proxy-dns
    networks: 
      net_smb:
        ipv4_address: 172.20.0.30
        aliases:
          - bind

  chrony:
    image: euca01/chrony:main
    cap_add:
      - ALL
    container_name: chrony
    restart: unless-stopped
    ports:
      - 123:123/udp
    env_file:
      - path: ./samba.env
        required: true
    environment:
      - LOG_LEVEL=0
      - NOCLIENTLOG=true
      - ENABLE_NTS=false
      - ENABLE_SYSCLK=true
    networks: 
      net_smb:
        ipv4_address: 172.20.0.40
        aliases:
          - chrony


  proxy-dns:
    image: euca01/dns-proxy-filter:main
    container_name: proxy-dns
    restart: unless-stopped
    env_file:
      - path: ./samba.env
        required: true
    environment:
      - upstreamServer=192.168.181.10:5353
      - listenAddr=:53
    depends_on:
      - samba
    networks: 
      net_smb:
        ipv4_address: 172.20.0.50
        aliases:
          - proxy-dns

networks:
  net_smb:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_smb